/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSpecAccess().getAlternatives(), "rule__Spec__Alternatives");
					put(grammarAccess.getPlatformTypeAccess().getAlternatives(), "rule__PlatformType__Alternatives");
					put(grammarAccess.getDatabaseNameAccess().getAlternatives(), "rule__DatabaseName__Alternatives");
					put(grammarAccess.getPrimitiveDataTypeAccess().getAlternatives(), "rule__PrimitiveDataType__Alternatives");
					put(grammarAccess.getDeploymentSpecAccess().getGroup(), "rule__DeploymentSpec__Group__0");
					put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
					put(grammarAccess.getDeviceAccess().getGroup_16(), "rule__Device__Group_16__0");
					put(grammarAccess.getDeviceLocationAccess().getGroup(), "rule__DeviceLocation__Group__0");
					put(grammarAccess.getDeviceProtocolAccess().getGroup(), "rule__DeviceProtocol__Group__0");
					put(grammarAccess.getDeviceAbilitiesAccess().getGroup(), "rule__DeviceAbilities__Group__0");
					put(grammarAccess.getDeviceAbilitiesAccess().getGroup_1(), "rule__DeviceAbilities__Group_1__0");
					put(grammarAccess.getInteractionSpecAccess().getGroup(), "rule__InteractionSpec__Group__0");
					put(grammarAccess.getInteractionActionAccess().getGroup(), "rule__InteractionAction__Group__0");
					put(grammarAccess.getArchSpecAccess().getGroup(), "rule__ArchSpec__Group__0");
					put(grammarAccess.getArchSpecAccess().getGroup_0(), "rule__ArchSpec__Group_0__0");
					put(grammarAccess.getArchSpecAccess().getGroup_5(), "rule__ArchSpec__Group_5__0");
					put(grammarAccess.getInBuiltComputationalServiceAccess().getGroup(), "rule__InBuiltComputationalService__Group__0");
					put(grammarAccess.getInBuiltComputationalServiceAccess().getGroup_5(), "rule__InBuiltComputationalService__Group_5__0");
					put(grammarAccess.getCustomComputationalServiceAccess().getGroup(), "rule__CustomComputationalService__Group__0");
					put(grammarAccess.getRequestAccess().getGroup(), "rule__Request__Group__0");
					put(grammarAccess.getConsumeForInBuiltAccess().getGroup(), "rule__ConsumeForInBuilt__Group__0");
					put(grammarAccess.getConsumeAccess().getGroup(), "rule__Consume__Group__0");
					put(grammarAccess.getCommandAccess().getGroup(), "rule__Command__Group__0");
					put(grammarAccess.getCommandParameterAccess().getGroup(), "rule__CommandParameter__Group__0");
					put(grammarAccess.getCommandParameterAccess().getGroup_1(), "rule__CommandParameter__Group_1__0");
					put(grammarAccess.getVocSpecAccess().getGroup(), "rule__VocSpec__Group__0");
					put(grammarAccess.getRegionAccess().getGroup(), "rule__Region__Group__0");
					put(grammarAccess.getStructAccess().getGroup(), "rule__Struct__Group__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getPeriodicSensorsAccess().getGroup(), "rule__PeriodicSensors__Group__0");
					put(grammarAccess.getEventSensorsAccess().getGroup(), "rule__EventSensors__Group__0");
					put(grammarAccess.getEventConditionsAccess().getGroup(), "rule__EventConditions__Group__0");
					put(grammarAccess.getEventConditionsAccess().getGroup_1(), "rule__EventConditions__Group_1__0");
					put(grammarAccess.getGenerateAccess().getGroup(), "rule__Generate__Group__0");
					put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getParametersAccess().getGroup(), "rule__Parameters__Group__0");
					put(grammarAccess.getStorageServiceAccess().getGroup(), "rule__StorageService__Group__0");
					put(grammarAccess.getDataAccessAccess().getGroup(), "rule__DataAccess__Group__0");
					put(grammarAccess.getSpecAccess().getVocSpecAssignment_0(), "rule__Spec__VocSpecAssignment_0");
					put(grammarAccess.getSpecAccess().getInteractionSpecAssignment_1(), "rule__Spec__InteractionSpecAssignment_1");
					put(grammarAccess.getSpecAccess().getArchSpecAssignment_2(), "rule__Spec__ArchSpecAssignment_2");
					put(grammarAccess.getSpecAccess().getNetworkSpecAssignment_3(), "rule__Spec__NetworkSpecAssignment_3");
					put(grammarAccess.getDeploymentSpecAccess().getDevicesAssignment_2(), "rule__DeploymentSpec__DevicesAssignment_2");
					put(grammarAccess.getDeviceAccess().getDeviceNameAssignment_0(), "rule__Device__DeviceNameAssignment_0");
					put(grammarAccess.getDeviceAccess().getDeviceLocationAssignment_4(), "rule__Device__DeviceLocationAssignment_4");
					put(grammarAccess.getDeviceAccess().getPlatformTypeAssignment_7(), "rule__Device__PlatformTypeAssignment_7");
					put(grammarAccess.getDeviceAccess().getDeviceAbilitiesAssignment_11(), "rule__Device__DeviceAbilitiesAssignment_11");
					put(grammarAccess.getDeviceAccess().getDeviceProtocolAssignment_15(), "rule__Device__DeviceProtocolAssignment_15");
					put(grammarAccess.getDeviceAccess().getDatabaseNameAssignment_16_2(), "rule__Device__DatabaseNameAssignment_16_2");
					put(grammarAccess.getDeviceAccess().getDeviceDescriptionAssignment_19(), "rule__Device__DeviceDescriptionAssignment_19");
					put(grammarAccess.getDeviceDescriptionAccess().getDevicedescriptionTextAssignment(), "rule__DeviceDescription__DevicedescriptionTextAssignment");
					put(grammarAccess.getDeviceLocationAccess().getRegionLabelAssignment_0(), "rule__DeviceLocation__RegionLabelAssignment_0");
					put(grammarAccess.getDeviceLocationAccess().getRegionValueAssignment_2(), "rule__DeviceLocation__RegionValueAssignment_2");
					put(grammarAccess.getPlatformTypeAccess().getDeviceTypeAssignment_0(), "rule__PlatformType__DeviceTypeAssignment_0");
					put(grammarAccess.getPlatformTypeAccess().getDeviceTypeAssignment_1(), "rule__PlatformType__DeviceTypeAssignment_1");
					put(grammarAccess.getDatabaseNameAccess().getInstalledDatabaseAssignment_0(), "rule__DatabaseName__InstalledDatabaseAssignment_0");
					put(grammarAccess.getDatabaseNameAccess().getInstalledDatabaseAssignment_1(), "rule__DatabaseName__InstalledDatabaseAssignment_1");
					put(grammarAccess.getDatabaseNameAccess().getInstalledDatabaseAssignment_2(), "rule__DatabaseName__InstalledDatabaseAssignment_2");
					put(grammarAccess.getDeviceProtocolAccess().getProtocolNameAssignment_0(), "rule__DeviceProtocol__ProtocolNameAssignment_0");
					put(grammarAccess.getDeviceAbilitiesAccess().getDeviceEntityNameAssignment_0(), "rule__DeviceAbilities__DeviceEntityNameAssignment_0");
					put(grammarAccess.getDeviceAbilitiesAccess().getNameAssignment_1_1(), "rule__DeviceAbilities__NameAssignment_1_1");
					put(grammarAccess.getInteractionSpecAccess().getInteractionNameAssignment_4(), "rule__InteractionSpec__InteractionNameAssignment_4");
					put(grammarAccess.getInteractionSpecAccess().getInteractionCommandAssignment_5(), "rule__InteractionSpec__InteractionCommandAssignment_5");
					put(grammarAccess.getInteractionSpecAccess().getInteractionRequestAssignment_6(), "rule__InteractionSpec__InteractionRequestAssignment_6");
					put(grammarAccess.getInteractionSpecAccess().getInteractionNotifyAssignment_7(), "rule__InteractionSpec__InteractionNotifyAssignment_7");
					put(grammarAccess.getInteractionActionAccess().getActionNameAssignment_1(), "rule__InteractionAction__ActionNameAssignment_1");
					put(grammarAccess.getInteractionActionAccess().getParametersAssignment_3(), "rule__InteractionAction__ParametersAssignment_3");
					put(grammarAccess.getInteractionActionAccess().getInteractionEntityAssignment_6(), "rule__InteractionAction__InteractionEntityAssignment_6");
					put(grammarAccess.getArchSpecAccess().getStructsAssignment_0_2(), "rule__ArchSpec__StructsAssignment_0_2");
					put(grammarAccess.getArchSpecAccess().getInbuiltComputationalServiceAssignment_6(), "rule__ArchSpec__InbuiltComputationalServiceAssignment_6");
					put(grammarAccess.getArchSpecAccess().getCustomComputationalServiceAssignment_9(), "rule__ArchSpec__CustomComputationalServiceAssignment_9");
					put(grammarAccess.getInBuiltComputationalServiceAccess().getInBuiltComputationalServiceNameAssignment_0(), "rule__InBuiltComputationalService__InBuiltComputationalServiceNameAssignment_0");
					put(grammarAccess.getInBuiltComputationalServiceAccess().getConsumesAssignment_1(), "rule__InBuiltComputationalService__ConsumesAssignment_1");
					put(grammarAccess.getInBuiltComputationalServiceAccess().getOperationNameAssignment_4(), "rule__InBuiltComputationalService__OperationNameAssignment_4");
					put(grammarAccess.getInBuiltComputationalServiceAccess().getOperationParameterAssignment_5_1(), "rule__InBuiltComputationalService__OperationParameterAssignment_5_1");
					put(grammarAccess.getInBuiltComputationalServiceAccess().getGenerateInfoAssignment_8(), "rule__InBuiltComputationalService__GenerateInfoAssignment_8");
					put(grammarAccess.getCustomComputationalServiceAccess().getCustomComputationalServiceNameAssignment_0(), "rule__CustomComputationalService__CustomComputationalServiceNameAssignment_0");
					put(grammarAccess.getCustomComputationalServiceAccess().getConsumesAssignment_1(), "rule__CustomComputationalService__ConsumesAssignment_1");
					put(grammarAccess.getCustomComputationalServiceAccess().getRequestsAssignment_2(), "rule__CustomComputationalService__RequestsAssignment_2");
					put(grammarAccess.getCustomComputationalServiceAccess().getGenerateInfoAssignment_3(), "rule__CustomComputationalService__GenerateInfoAssignment_3");
					put(grammarAccess.getCustomComputationalServiceAccess().getCommandsAssignment_4(), "rule__CustomComputationalService__CommandsAssignment_4");
					put(grammarAccess.getRequestAccess().getRequestnameAssignment_1(), "rule__Request__RequestnameAssignment_1");
					put(grammarAccess.getRequestAccess().getStorageForRequestAssignment_3(), "rule__Request__StorageForRequestAssignment_3");
					put(grammarAccess.getConsumeForInBuiltAccess().getNameAssignment_1(), "rule__ConsumeForInBuilt__NameAssignment_1");
					put(grammarAccess.getConsumeForInBuiltAccess().getSensorForConsumeAssignment_3(), "rule__ConsumeForInBuilt__SensorForConsumeAssignment_3");
					put(grammarAccess.getConsumeAccess().getNameAssignment_1(), "rule__Consume__NameAssignment_1");
					put(grammarAccess.getConsumeAccess().getFromNameAssignment_3(), "rule__Consume__FromNameAssignment_3");
					put(grammarAccess.getCommandAccess().getCommandNameAssignment_1(), "rule__Command__CommandNameAssignment_1");
					put(grammarAccess.getCommandAccess().getCommandparameterAssignment_3(), "rule__Command__CommandparameterAssignment_3");
					put(grammarAccess.getCommandAccess().getActuatorForCommandAssignment_6(), "rule__Command__ActuatorForCommandAssignment_6");
					put(grammarAccess.getCommandParameterAccess().getNameAssignment_0(), "rule__CommandParameter__NameAssignment_0");
					put(grammarAccess.getCommandParameterAccess().getParameterAssignment_1_1(), "rule__CommandParameter__ParameterAssignment_1_1");
					put(grammarAccess.getVocSpecAccess().getStructsAssignment_2(), "rule__VocSpec__StructsAssignment_2");
					put(grammarAccess.getVocSpecAccess().getPeriodicSensorsAssignment_9(), "rule__VocSpec__PeriodicSensorsAssignment_9");
					put(grammarAccess.getVocSpecAccess().getEventSensorsAssignment_12(), "rule__VocSpec__EventSensorsAssignment_12");
					put(grammarAccess.getVocSpecAccess().getActuatorsAssignment_15(), "rule__VocSpec__ActuatorsAssignment_15");
					put(grammarAccess.getVocSpecAccess().getStorageServiceAssignment_18(), "rule__VocSpec__StorageServiceAssignment_18");
					put(grammarAccess.getRegionAccess().getRegionLabelAssignment_0(), "rule__Region__RegionLabelAssignment_0");
					put(grammarAccess.getRegionAccess().getRegionTypeAssignment_2(), "rule__Region__RegionTypeAssignment_2");
					put(grammarAccess.getRegionLabelAccess().getNameAssignment(), "rule__RegionLabel__NameAssignment");
					put(grammarAccess.getStructAccess().getNameAssignment_0(), "rule__Struct__NameAssignment_0");
					put(grammarAccess.getStructAccess().getFieldsAssignment_1(), "rule__Struct__FieldsAssignment_1");
					put(grammarAccess.getFieldAccess().getNameAssignment_0(), "rule__Field__NameAssignment_0");
					put(grammarAccess.getFieldAccess().getTypeAssignment_2(), "rule__Field__TypeAssignment_2");
					put(grammarAccess.getPeriodicSensorsAccess().getSensorNameAssignment_0(), "rule__PeriodicSensors__SensorNameAssignment_0");
					put(grammarAccess.getPeriodicSensorsAccess().getGenerateInfoAssignment_1(), "rule__PeriodicSensors__GenerateInfoAssignment_1");
					put(grammarAccess.getEventSensorsAccess().getSensorNameAssignment_0(), "rule__EventSensors__SensorNameAssignment_0");
					put(grammarAccess.getEventSensorsAccess().getGenerateInfoAssignment_1(), "rule__EventSensors__GenerateInfoAssignment_1");
					put(grammarAccess.getEventSensorsAccess().getEventConditionsAssignment_3(), "rule__EventSensors__EventConditionsAssignment_3");
					put(grammarAccess.getEventConditionsAccess().getNameAssignment_0(), "rule__EventConditions__NameAssignment_0");
					put(grammarAccess.getEventConditionsAccess().getEventConditionsAssignment_1_1(), "rule__EventConditions__EventConditionsAssignment_1_1");
					put(grammarAccess.getInBuiltComputationalServiceNameAccess().getNameAssignment(), "rule__InBuiltComputationalServiceName__NameAssignment");
					put(grammarAccess.getEntityNameAccess().getNameAssignment(), "rule__EntityName__NameAssignment");
					put(grammarAccess.getGenerateAccess().getSourceNameAssignment_1(), "rule__Generate__SourceNameAssignment_1");
					put(grammarAccess.getGenerateAccess().getTypeAssignment_3(), "rule__Generate__TypeAssignment_3");
					put(grammarAccess.getSourceNameAccess().getNameAssignment(), "rule__SourceName__NameAssignment");
					put(grammarAccess.getActuatorAccess().getActuatorNameAssignment_0(), "rule__Actuator__ActuatorNameAssignment_0");
					put(grammarAccess.getActuatorAccess().getActionsAssignment_1(), "rule__Actuator__ActionsAssignment_1");
					put(grammarAccess.getActionAccess().getActionNameAssignment_1(), "rule__Action__ActionNameAssignment_1");
					put(grammarAccess.getActionAccess().getParametersAssignment_3(), "rule__Action__ParametersAssignment_3");
					put(grammarAccess.getActionNameAccess().getNameAssignment(), "rule__ActionName__NameAssignment");
					put(grammarAccess.getParametersAccess().getParameterNameAssignment_0(), "rule__Parameters__ParameterNameAssignment_0");
					put(grammarAccess.getParametersAccess().getTypeAssignment_2(), "rule__Parameters__TypeAssignment_2");
					put(grammarAccess.getParameterNameAccess().getNameAssignment(), "rule__ParameterName__NameAssignment");
					put(grammarAccess.getStorageServiceAccess().getStorageServiceNameAssignment_0(), "rule__StorageService__StorageServiceNameAssignment_0");
					put(grammarAccess.getStorageServiceAccess().getDataAccessesAssignment_1(), "rule__StorageService__DataAccessesAssignment_1");
					put(grammarAccess.getDataAccessAccess().getSourceNameAssignment_1(), "rule__DataAccess__SourceNameAssignment_1");
					put(grammarAccess.getDataAccessAccess().getDataAccessTypeAssignment_3(), "rule__DataAccess__DataAccessTypeAssignment_3");
					put(grammarAccess.getDataAccessAccess().getDataItemAssignment_5(), "rule__DataAccess__DataItemAssignment_5");
					put(grammarAccess.getDataAccessAccess().getTypeAssignment_7(), "rule__DataAccess__TypeAssignment_7");
					put(grammarAccess.getDataAccessAccess().getActionsAssignment_9(), "rule__DataAccess__ActionsAssignment_9");
					put(grammarAccess.getTypeAccess().getPrimitiveDataTypeAssignment(), "rule__Type__PrimitiveDataTypeAssignment");
					put(grammarAccess.getOperationNameAccess().getOPERATION_NAMEAssignment(), "rule__OperationName__OPERATION_NAMEAssignment");
					put(grammarAccess.getPrimitiveDataTypeAccess().getINTEGERAssignment_0(), "rule__PrimitiveDataType__INTEGERAssignment_0");
					put(grammarAccess.getPrimitiveDataTypeAccess().getBOOLEANAssignment_1(), "rule__PrimitiveDataType__BOOLEANAssignment_1");
					put(grammarAccess.getPrimitiveDataTypeAccess().getSTRINGAssignment_2(), "rule__PrimitiveDataType__STRINGAssignment_2");
					put(grammarAccess.getPrimitiveDataTypeAccess().getLONGAssignment_3(), "rule__PrimitiveDataType__LONGAssignment_3");
					put(grammarAccess.getPrimitiveDataTypeAccess().getDOUBLEAssignment_4(), "rule__PrimitiveDataType__DOUBLEAssignment_4");
					put(grammarAccess.getPrimitiveDataTypeAccess().getStructDefAssignment_5(), "rule__PrimitiveDataType__StructDefAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleSpec();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
